language: ruby
rvm:
  - 2.4.1

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
install: gem install jekyll html-proofer
script: jekyll build && htmlproofer ./_site

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN_COURSL3
  keep-history: true
local_dir: site