language: python
install:
  - pip install mkdocs
  - pip install mkdocs-material
script:
  - mkdocs build --clean --strict
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN_COURSL3
  keep-history: true
  local_dir: site
