site_name: Cours de Licence 3
docs_dir: Docs/

theme:
  name: material
  palette:
    primary: 'Lime'
    accent: 'Yellow'
  feature:
    tabs: true
  language: "fr"
  
extra:
  social:
    - type: "github"
      link: "https://github.com/Lizeem"
    - type: "linkedin"
      link: "https://www.linkedin.com/in/emma-lizeski-837899149/"